name: Run FE Assignment Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run test -- --json --outputFile=report.json
      - run: npm run analyze
      - name: Upload report and summary
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: |
            report.json
            summary.txt
